// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        string `json:"id"`
	Filename  string `json:"filename"`
	Sha512sum string `json:"sha512sum"`
}

type Record struct {
	ID            string        `json:"id"`
	Userid        string        `json:"userid"`
	Fileid        string        `json:"fileid"`
	Duration      pgtype.Float8 `json:"duration"`
	Distance      pgtype.Float8 `json:"distance"`
	Ascent        pgtype.Float8 `json:"ascent"`
	Descent       pgtype.Float8 `json:"descent"`
	Elevationdiff pgtype.Float8 `json:"elevationdiff"`
	Trails        pgtype.Text   `json:"trails"`
	Rawdata       pgtype.Text   `json:"rawdata"`
}

type User struct {
	ID string `json:"id"`
}
