// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkInsertFiles(ctx context.Context, arg []BulkInsertFilesParams) (int64, error)
	BulkInsertRecord(ctx context.Context, arg []BulkInsertRecordParams) (int64, error)
	DeleteFileById(ctx context.Context, id string) error
	DeleteFileByName(ctx context.Context, filename string) error
	DeleteRecordByFileId(ctx context.Context, fileid string) error
	DeleteRecordById(ctx context.Context, id string) error
	DeleteRecordsByUserId(ctx context.Context, userid string) error
	DeleteUser(ctx context.Context, id string) error
	DropFiles(ctx context.Context) error
	DropRecords(ctx context.Context) error
	DropUsers(ctx context.Context) error
	GetFileById(ctx context.Context, id string) (File, error)
	GetFileByName(ctx context.Context, filename string) (File, error)
	GetRecordByFileId(ctx context.Context, fileid string) (Record, error)
	GetRecordById(ctx context.Context, id string) (Record, error)
	GetRecordsByTrail(ctx context.Context, trails pgtype.Text) ([]Record, error)
	GetRecordsByUserId(ctx context.Context, userid string) ([]Record, error)
	GetRecordsOfUserOnTrail(ctx context.Context, arg GetRecordsOfUserOnTrailParams) ([]Record, error)
	GetUserById(ctx context.Context, id string) (string, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertRecord(ctx context.Context, arg InsertRecordParams) (Record, error)
	InsertUser(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
